modLoader="javafml"
loaderVersion="[38,)"
license="GNU GPLv3"

[[mods]]
modId="persistentbits"
version="${file.jarVersion}"
displayName="Persistent Bits"
displayURL="http://github.com/oitsjustjose/persistent-bits"
credits=""
authors="oitsjustjose"
description='''# A super simple chunk-loading mod which works across world loads - uses the vanilla /forceload mechanic!'''

[[dependencies.persistentbits]]
    modId="forge"
    mandatory=true
    versionRange="[38,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.persistentbits]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18,)"
    ordering="NONE"
    side="BOTH"
